### ISSUE TITLE
incorrect logo

### ISSUE THREAD

**Issue by NotNapper** [Metabolix/HackBGRT#42] opened 2019-08-17 04:48 UTC
Hello, I installed the tool and tried several times to have a logo that suits me but when I boot my pc, my logo appear but a second before the loading finishes my first logo (first modification) reappears. If you don't understand tell me and I will do a video.

**Comment by fuzepod** [comment] 2019-08-17 04:56
I am also having this issue, complete removal and reinstall did not fix it

**Comment by NotNapper** [comment] 2019-08-17 05:42
Ok, I think I've found, you have to restart your computer by the "Restart" option, not shutdown and start. For me it works.

**Comment by sylveon** [comment] 2019-08-17 18:30
Duplicate of #32

**Comment by fuzepod** [comment] 2019-08-17 19:16
> Ok, I think I've found, you have to restart your computer by the "Restart" option, not shutdown and start. For me it works.

Thanks! That fixed it. 


> Duplicate of #32

It is not a duplicate of #32, I know what my BIOS logo is. The problem we had is caused by setting a custom boot logo, and then changing it to a different logo. The problem is the new logo shows up but right before the boot logo finishes and the lock screen appears, the old custom logo flashes for a second. The problem is fixed by choosing the "Restart" option to shutdown the computer.

I still have an issue where before right before the lockscreen shows up I get a flash of orange/white on different parts of the screen. I had this issue show up before, right after the old logo flashed for a second. Do you have that issue @NotNapper ?

**Comment by NotNapper** [comment] 2019-08-17 23:20
Nope sorry I don't have this issue. For me it work perfectly fine @fuzeprod

**Closed** 2019-08-21 04:45 UTC

**Comment by fuzepod** [comment] 2019-09-10 00:59
Just wanted to update, I got a slightly upgraded graphics card and the flashing light problem has gone away. Seems to be the fault of the low performance card, all set now.
