### ISSUE TITLE
Can't get onto computer

### ISSUE THREAD

**Issue by MobileData2** [Metabolix/HackBGRT#10] opened 2017-08-08 07:49 UTC
Got error message by changing the config wrongly by accident: 
HackBGRT: Failed to load BMP (C:\splash.bmp) !
HackBGRT: LoadImage for new image (C:\splash.bmp) failed
Hack BGRT has failed. Use parameter debug=1 for details.
HackBGRT version: v1.2.0
anyway to undo the issue?

**Comment by MobileData2** [comment] 2017-08-10 02:09
Anyone?

**Comment by charlesmilette** [comment] 2017-08-12 01:34
Boot a Linux or windows live cd and repair the issue manually by mounting
the EFI partition and editing the HackBGRT config file

**Comment by Metabolix** [comment] 2017-08-28 19:02
You have three options:
* Use a Windows repair disk (or installation disk) to restore the original boot loader.
* Use Linux or another OS to edit the configuration file.
* Try to get to the UEFI shell (if you have one) and manually boot Windows there with something like `FS0:\EFI\HackBGRT\bootmgfw-original.efi`, and then fix the config.
I'm closing the issue because this is clearly a configuration error and not a bug.

**Closed by Metabolix** 2017-08-28 19:02 UTC

**Comment by Metabolix** [comment] 2017-08-28 23:29
Version 1.4.0 (released just now) includes a failsafe for this kind of error: If the `boot=` line is invalid (for example, points to a BMP instead of a boot loader), HackBGRT will try with the default path (`boot=\EFI\HackBGRT\bootmgfw-original.efi`).
