### ISSUE TITLE
Error: Couldn't copy new HackBGRT over the MS loader (bootmgfw.efi).

### ISSUE THREAD

**Issue by SaminYaser-work** [Metabolix/HackBGRT#30] opened 2018-10-20 17:36 UTC
Facing this error after closing paint.

**Comment by Metabolix** [comment] 2018-11-03 11:14
Interesting. Can you open a Command Prompt as admin ([like this](https://www.google.com/search?q=windows+open+command+prompt+admin)) and post the output of the following commands:

    mountvol Z: /S
    dir Z:\EFI\Microsoft\Boot\*.efi
    attrib Z:\EFI\Microsoft\Boot\*.efi
    dir Z:\EFI\HackBGRT\*.efi
    attrib Z:\EFI\HackBGRT\*.efi
    mountvol Z: /D

**Comment by F00dCHAiN** [comment] 2018-11-16 07:40
Here you go.

> C:\Windows\system32>mountvol Z: /S
> 
> C:\Windows\system32>dir Z:\EFI\Microsoft\Boot\*.efi
>  Volume in drive Z has no label.
>  Volume Serial Number is 1094-0E39
> 
>  Directory of Z:\EFI\Microsoft\Boot
> 
> 20-Oct-18  10:26 PM         1,273,864 bootmgfw.efi
> 20-Oct-18  10:26 PM         1,257,456 bootmgr.efi
> 20-Oct-18  10:26 PM         1,103,840 memtest.efi
>                3 File(s)      3,635,160 bytes
>                0 Dir(s)      86,240,256 bytes free
> 
> C:\Windows\system32>attrib Z:\EFI\Microsoft\Boot\*.efi
> A                    Z:\EFI\Microsoft\Boot\bootmgfw.efi
> A                    Z:\EFI\Microsoft\Boot\bootmgr.efi
> A                    Z:\EFI\Microsoft\Boot\memtest.efi
> 
> C:\Windows\system32>dir Z:\EFI\HackBGRT\*.efi
> The system cannot find the file specified.
> 
> C:\Windows\system32>attrib Z:\EFI\HackBGRT\*.efi
> Path not found - Z:\EFI\HackBGRT
> 
> C:\Windows\system32>mountvol Z: /D

**Comment by Metabolix** [comment] 2018-11-16 07:56
Thanks! However, in the latter commands, I asked for `Z:\EFI\HackBGRT\*.efi` and not `Z:\EFI\HackBGRT*.efi`, notice `\*`. Does that give similar errors?

**Comment by F00dCHAiN** [comment] 2018-11-16 13:56
I guess so. here it is again.

> C:\Windows\system32>dir Z:\EFI\Microsoft\Boot\*.efi
>  Volume in drive Z has no label.
>  Volume Serial Number is 1094-0E39
> 
>  Directory of Z:\EFI\Microsoft\Boot
> 
> 20-Oct-18  10:26 PM         1,273,864 bootmgfw.efi
> 20-Oct-18  10:26 PM         1,257,456 bootmgr.efi
> 20-Oct-18  10:26 PM         1,103,840 memtest.efi
>                3 File(s)      3,635,160 bytes
>                0 Dir(s)      86,240,256 bytes free
> 
> C:\Windows\system32>attrib Z:\EFI\Microsoft\Boot\*.efi
> A                    Z:\EFI\Microsoft\Boot\bootmgfw.efi
> A                    Z:\EFI\Microsoft\Boot\bootmgr.efi
> A                    Z:\EFI\Microsoft\Boot\memtest.efi
> 
> C:\Windows\system32>dir Z:\EFI\HackBGRT\*.efi
> The system cannot find the file specified.
> 
> C:\Windows\system32>attrib Z:\EFI\HackBGRT\*.efi
> Path not found - Z:\EFI\HackBGRT
> 
> C:\Windows\system32>mountvol Z: /D

**Comment by F00dCHAiN** [comment] 2018-11-16 13:59
Ok for some reason its automatically removing the \ when I comment. Here's a pic: https://imgur.com/a/i3E1lSJ

**Comment by QuentinMarical** [comment] 2018-12-10 16:03
Take ownership on all .efi files and i'ts work for me

**Comment by CRKatri** [comment] 2020-07-26 02:46
I'm facing the same issue

**Comment by YaoYinYing** [comment] 2022-03-21 05:46
Solved. This problem is caused by boot partition is devided from your system drive. You need to mount your EFI drive (maynot be your C drive) first,
`mountvol Z: /S`
 and Install HackBGRT by following the instruction.

**Comment by niu2023** [comment] 2022-08-08 05:09
i found an easy way to sove this problem. just rename your C:\EFI folder to others like EFI2, then use the application like usual. after that you can rename C:\EFI folder back or not, it doesn't affect your boot

**Comment by Metabolix** [comment] 2023-09-10 14:58
I'd appreciate a new try with the most recent release (2.0.0), and if this still happens, `setup.log` might be useful for debugging.

**Comment by Metabolix** [comment] 2023-11-17 21:37
Closing bugs from obsolete versions. Please reopen if this is still valid for the most recent version.

**Closed by Metabolix** 2023-11-17 21:37 UTC
Labels: needs input
